name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/node
      - run: pnpm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/node
      - run: pnpm run build
      - name: Log run number, attempt and id
        run: |
          echo "Run number: ${{ github.run_number }}"
      - name: Update manifest.json version
        run: jq --arg version "1.0.${{ github.run_number }}" '.version = $version' public/manifest.json > dist/manifest.json
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  deploy-chrome-store:
    if: github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: chrome-store
      url: https://chrome.google.com/webstore/detail/motivation/${{ vars.CHROME_EXTENSION_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - run: zip -r dist.zip ./dist
      - uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: ./dist.zip
          extension-id: ${{ vars.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: false
